#!/usr/bin/env bash
# Check for root privileges
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Install Nginx if not already installed
apt-get update -y
apt-get install -y nginx

# Add redirection to the default site configuration
sed -i "/^}$/i \\
    location /redirect_me { \\
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \\
    }" /etc/nginx/sites-available/default

# Reload Nginx to apply changes
service nginx reload


if [ "$(curl -s -o /dev/null -w "%{http_code}" http://localhost/redirect_me)" == "301" ]; then
  echo "Redirection working as expected."
else
  echo "Redirection failed."
fi
