#!/usr/bin/env bash
# Install Nginx and set up the redirection configuration
sudo apt-get update
sudo apt-get install -y nginx

# Append the redirect location block to the Nginx default configuration
sudo bash -c 'cat << EOF >> /etc/nginx/sites-available/default

# Add location block for redirection
location = /redirect_me {
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}
EOF'

# Test and reload Nginx
sudo nginx -t && sudo systemctl reload nginx
