#!/usr/bin/env bash
# Ensure script is run as root
if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Append 404 error configuration to Nginx
cat << EOF >> /etc/nginx/sites-available/default

# Custom 404 error page configuration
error_page 404 /custom_404.html;
location = /custom_404.html {
    root /var/www/html;
    internal;
}
EOF

# Test and reload Nginx
nginx -t && systemctl reload nginx
echo "Testing errorpage:"
curl -o /dev/null -s -w "%{http_code}\n" http://localhost/hello
